# Generated by Django 6.0.4 on 2026-04-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fat',
            new_name='fats',
        ),
    ]
